import type { EvidenceDocument } from "@/lib/evidence";

/**
 * A sample evidence pack, generated by the same code as a real one, so an
 * accountant can forward the actual file to whoever has to accept it before
 * anyone pays. Everything in it is invented and says so: the order reference
 * reads SAMPLE, the VAT numbers are the made-up format examples, and the
 * company names are fictional. The German row has no name or address because
 * a real one never does.
 */
export const SAMPLE_GENERATED_AT = new Date("2026-10-04T09:00:00.000Z");

export const SAMPLE_EVIDENCE: EvidenceDocument = (() => {
  const rows: EvidenceDocument["rows"] = [
    {
      position: 1,
      vatNumber: "SE123456789001",
      status: "valid",
      consultationNumber: "WAPIAAAAaSAMPLE1",
      requestDate: "2026-10-04T08:59:41Z",
      traderName: "EXEMPEL HANDEL AB (SAMPLE)",
      traderAddress: "EXEMPELGATAN 1, 123 45 STOCKHOLM",
      note: null,
    },
    {
      position: 2,
      vatNumber: "DE123456789",
      status: "valid",
      consultationNumber: "WAPIAAAAaSAMPLE2",
      requestDate: "2026-10-04T08:59:42Z",
      traderName: null,
      traderAddress: null,
      note: null,
    },
    {
      position: 3,
      vatNumber: "FR12345678901",
      status: "valid",
      consultationNumber: "00000000-5a3e-4000-8000-000000000003",
      requestDate: "2026-10-04T08:59:42Z",
      traderName: "SOCIETE EXEMPLE SAS (SAMPLE)",
      traderAddress: "1 RUE DE L'EXEMPLE, 75000 PARIS",
      note: null,
    },
    {
      position: 4,
      vatNumber: "NL123456789B01",
      status: "invalid",
      consultationNumber: null,
      requestDate: "2026-10-04T08:59:43Z",
      traderName: null,
      traderAddress: null,
      note: null,
    },
    {
      position: 5,
      vatNumber: "IE1234567T",
      status: "valid",
      consultationNumber: "WAPIAAAAaSAMPLE5",
      requestDate: "2026-10-04T08:59:43Z",
      traderName: "EXAMPLE TRADING LIMITED (SAMPLE)",
      traderAddress: "1 SAMPLE STREET, DUBLIN",
      note: null,
    },
    {
      position: 6,
      vatNumber: "PL1234567890",
      status: "unverifiable",
      consultationNumber: null,
      requestDate: null,
      traderName: null,
      traderAddress: null,
      note: "MS_UNAVAILABLE - refunded automatically",
    },
  ];
  return {
    orderReference: "SAMPLE - not evidence of any check",
    requesterVat: "SE123456789001",
    rowCount: rows.length,
    validCount: rows.filter((r) => r.status === "valid").length,
    invalidCount: rows.filter((r) => r.status === "invalid").length,
    unverifiableCount: rows.filter((r) => r.status === "unverifiable").length,
    rows,
  };
})();
